// Standalone Android library build for the Trillboards CTV Measurement SDK.
// Auto-generated by scripts/sdk-mirror/sync-ctv-measurement.sh from
// trillboard-ctv/{agent-core-lite,discovery-core,trillboards-measurement-sdk}.
//
// Targets the camera-less appliance segment (vending / ATM / EV charging /
// smart kiosks). Produces a single fat AAR with BLE / WiFi / mDNS / SSDP /
// HTTP-probe / native-sensor capture; consumable on AGP 4.1+ + Jetifier.

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    `maven-publish`
}

android {
    namespace = "com.trillboards.measurement"
    compileSdk = 34

    defaultConfig {
        minSdk = 24
        targetSdk = 34
        consumerProguardFiles("consumer-proguard-rules.pro")
        ndk { abiFilters += listOf("arm64-v8a", "armeabi-v7a") }
    }

    compileOptions {
        // Java 1.8 → class v52 bytecode. Jetifier 1.0.0-beta10 (ASM 8) can
        // rewrite up to v58. AGP 4.1 + Jetifier consumers (legacy retail
        // appliance partners) get a clean dex path.
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    buildFeatures {
        buildConfig = false
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

publishing {
    publications {
        register<MavenPublication>("release") {
            groupId = "com.github.trillboards"
            artifactId = "ctv-measurement-sdk"
            version = providers.gradleProperty("version").getOrElse("1.0.0")
            afterEvaluate { from(components["release"]) }
        }
    }
}

dependencies {
    // ── AndroidX foundation ────────────────────────────────────────────────
    implementation("androidx.core:core-ktx:1.10.1")
    implementation("androidx.localbroadcastmanager:localbroadcastmanager:1.1.0")
    implementation("androidx.activity:activity-ktx:1.8.2")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.6.2")

    // ── Kotlin coroutines ──────────────────────────────────────────────────
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")

    // ── Networking (heartbeat + HTTP probe + socket.io bridge) ─────────────
    implementation("io.socket:socket.io-client:2.1.0") {
        exclude(group = "org.json", module = "json")
    }
    implementation("com.squareup.okhttp3:okhttp:4.11.0")
    implementation("com.squareup.okhttp3:logging-interceptor:4.11.0")

    // ── Identity / consent / ad bridge ─────────────────────────────────────
    implementation("com.google.android.gms:play-services-ads-identifier:18.0.1")
    implementation("com.google.android.gms:play-services-ads-lite:23.6.0")
    implementation("com.google.android.ump:user-messaging-platform:4.0.0")
    implementation("com.google.android.gms:play-services-location:21.0.1")

    // ── WebRTC for optional MDM remote view/control ────────────────────────
    implementation("com.infobip:google-webrtc:1.0.45036")

    // ── JNA — required by the UniFFI-generated discovery bindings ──────────
    implementation("net.java.dev.jna:jna:5.13.0@aar")
}
