// Standalone Android library build for the Trillboards CTV Measurement SDK.
// Auto-generated by scripts/sdk-mirror/sync-ctv-measurement.sh from
// trillboard-ctv/{agent-core-lite,discovery-core,trillboards-measurement-sdk}.
//
// Targets the camera-less appliance segment (vending / ATM / EV charging /
// smart kiosks). Produces a single fat AAR with BLE / WiFi / mDNS / SSDP /
// HTTP-probe / native-sensor capture; consumable on AGP 4.1+ + Jetifier.

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    `maven-publish`
}

android {
    namespace = "com.trillboards.measurement"
    // compileSdk tracks agent-core-lite (35). The curated source uses API-35 symbols
    // (e.g. BluetoothDevice.addressType in BleBeaconScanner). compileSdk is build-time
    // only — the AAR stays consumable on AGP 4.1 + minSdk 24 partners.
    compileSdk = 35

    defaultConfig {
        minSdk = 24
        targetSdk = 34
        consumerProguardFiles("consumer-proguard-rules.pro")
        ndk { abiFilters += listOf("arm64-v8a", "armeabi-v7a") }
    }

    compileOptions {
        // Java 1.8 → class v52 bytecode. Jetifier 1.0.0-beta10 (ASM 8) can
        // rewrite up to v58. AGP 4.1 + Jetifier consumers (legacy retail
        // appliance partners) get a clean dex path.
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    buildFeatures {
        buildConfig = false
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

publishing {
    publications {
        register<MavenPublication>("release") {
            groupId = "com.github.trillboards"
            artifactId = "ctv-measurement-sdk"
            version = providers.gradleProperty("version").getOrElse("1.0.0")
            afterEvaluate { from(components["release"]) }
        }
    }
}

dependencies {
    // Minimal POM by design — every dep below is justified by an actual import
    // somewhere in the curated source tree. Adding anything else here will
    // regress AGP 4.1 + Jetifier + compileSdk 30 partner builds. See the
    // section-3 source-allowlist comment for which monorepo packages produce
    // the imports each dep satisfies.

    // ── Kotlin coroutines ──────────────────────────────────────────────────
    // Used by every scanner (Dispatchers.IO + withContext + withTimeoutOrNull)
    // and by ScanScheduler / HeartbeatUploader in the SDK module.
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")

    // ── OkHttp 4.11 — heartbeat POST + HTTP probe ──────────────────────────
    // Pure JVM bytecode, Jetifier-clean, no compileSdk constraint.
    // Used by core/net/ApiClient.kt.
    implementation("com.squareup.okhttp3:okhttp:4.11.0")
    implementation("com.squareup.okhttp3:logging-interceptor:4.11.0")

    // ── JNA — required by the UniFFI-generated discovery bindings ──────────
    // (.aar variant ships the per-ABI native-lib loader; pure-Java, Jetifier-clean.)
    implementation("net.java.dev.jna:jna:5.13.0@aar")
}
