package com.trillboards.discovery

/**
 * Phase 3 — Thin Kotlin wrapper around the Rust `read_arp_with_oui()` UniFFI
 * binding.
 *
 * The Rust crate returns one [ArpEntry] per resolvable LAN neighbor (ARP
 * cache row with the `0x2` complete bit set), enriched at the Rust boundary
 * with an `oui_vendor` field looked up against the bundled IEEE OUI table.
 * On non-Linux hosts (the macOS build host JVM running unit tests) the
 * crate returns an empty list rather than throwing — this wrapper preserves
 * that contract.
 *
 * **NOT WIRED ON ANDROID** (verified 2026-05-02 on SM-X730 Android 13).
 * Android targetSdk ≥ 32 binds the app to the SELinux `untrusted_app_32`
 * (or higher) domain, which has `neverallow` rules on both `proc_net:file r`
 * (so `/proc/net/arp` returns `EACCES`) and
 * `netlink_route_socket nlmsg_getneigh` (so `RTM_GETNEIGH` returns `EPERM`).
 * The carve-out only allows `untrusted_app_25-30`. Play Store currently
 * mandates targetSdk ≥ 34 for new submissions, so dropping targetSdk is
 * not a viable production path. This adapter still ships in the AAR
 * because (a) the Rust core compiles into native libs we want for the
 * upcoming Linux/Windows kiosk SDK targets where `/proc/net/arp` is
 * readable, and (b) keeping the API stable lets future Android-version
 * policy reversals re-enable it with no agent-side change. The Android
 * tablet agent does NOT call this adapter — see
 * `tablet-agent/.../service/DeviceAgentService.kt` which emits
 * `arpDevices = null` on the heartbeat and replaces ARP-derived HTTP
 * probe targets with mDNS-discovered hosts + the WiFi gateway via
 * `WiFiSignalCollector.resolveGatewayIp`.
 *
 * **Why so thin?** All the parsing, classification, and OUI enrichment lives
 * in Rust where it can be unit-tested without an FFI hop. Kotlin's job is to
 * marshal the result up to whoever asked (the heartbeat collector) and
 * convert the throwable shape into something the agent's logging layer can
 * forward. The actual conversion is generated by UniFFI; we just expose the
 * function with the friendlier `Result<List<ArpEntry>>` shape Kotlin callers
 * expect.
 *
 * Failure handling: any [DiscoveryException] from the Rust side is wrapped
 * in a `Result.failure`. Callers SHOULD treat failure as "no rows" — the
 * heartbeat must still ship even when ARP read failed.
 */
object ArpAdapter {

    /**
     * Read the ARP cache and return one [ArpEntry] per resolvable LAN
     * neighbor.  Returns an empty list on platforms where `/proc/net/arp`
     * does not exist (macOS, Windows). Returns a `Result.failure` with the
     * underlying [DiscoveryException] on Io / Parse errors.
     *
     * Suspends nothing — the Rust call is synchronous and returns in <1 ms
     * on a typical Android home-LAN cache (<50 entries). Calling from a
     * non-main thread is the agent's responsibility.
     */
    fun read(): Result<List<ArpEntry>> = runCatching {
        // `readArpWithOui` is the top-level UniFFI-generated function in the
        // same `com.trillboards.discovery` package.
        readArpWithOui()
    }
}
